all:
	(cd timerLib && make install)
	(cd blink_demo && make)
	(cd button_demo && make)
	(cd buzzer_demo && make)
	(cd buttons && make)

clean:
	(cd timerLib && make clean)
	(cd blink_demo && make clean)
	(cd button_demo && make clean)
	(cd buzzer_demo && make clean)
	(cd buttons && make clean)
